# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigIntegerField(help_text='Unique identifier for this chat', primary_key=True, serialize=False, verbose_name='Chat ID')),
                ('type', models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], help_text='Type of chat', max_length=10, verbose_name='Type')),
                ('title', models.CharField(blank=True, help_text='Title, for supergroups, channels and group chats', max_length=128, null=True, verbose_name='Title')),
                ('username', models.CharField(blank=True, help_text='Username, for private chats, supergroups and channels if available', max_length=128, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, help_text='First name of the other party in a private chat', max_length=128, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, help_text='Last name of the other party in a private chat', max_length=128, null=True, verbose_name='Last name')),
                ('state', models.CharField(default='root', help_text='A short memory, to store the last command if the command have a flow with more than one message', max_length=128, verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('secret', models.CharField(max_length=16, verbose_name='Secret')),
                ('last_publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last publish')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_topics', to='bot.Chat', verbose_name='Owner')),
                ('subscribers', models.ManyToManyField(related_name='subscribed_topics', to='bot.Chat', verbose_name='Subscribers')),
            ],
        ),
    ]
